"""UTC datetime

Revision ID: 4ccd6d17fd81
Revises: 9e93ffcaf924
Create Date: 2022-01-10 02:13:34.259749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccd6d17fd81'
down_revision = '9e93ffcaf924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_whether_date', table_name='whether')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_whether_date', 'whether', ['date'], unique=False)
    # ### end Alembic commands ###
