"""Fist migration

Revision ID: 9e93ffcaf924
Revises: 
Create Date: 2021-07-19 07:11:53.615667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e93ffcaf924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('whether',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('experiment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experiment'], ['experiment.id'], name='fk_whether_experiment_id_experiment'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whether_date'), 'whether', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whether_date'), table_name='whether')
    op.drop_table('whether')
    op.drop_table('experiment')
    # ### end Alembic commands ###
