# docker-compose.yml

version: '3.4'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8001:80
    environment:
      - API_PATH
      - API_KEY
      - DATABASE_URL=postgresql://degrad:degrad@database:5432/degrad
      - MAX_WORKERS=1
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=(Host(`$HOST`) &&
        PathPrefix(`$API_PATH`))"
      - "traefik.http.routers.fastapi.middlewares=fastapi-stripprefix"
      - "traefik.http.middlewares.fastapi-stripprefix.stripprefix.prefixes=$API\
        _PATH"
    volumes:
      - "./api/alembic/versions:/app/alembic/versions"

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=degrad
      - POSTGRES_PASSWORD=degrad
      - POSTGRES_DB=degrad

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - 8002:3000
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - database
    # Configura proxy
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s${DASH_PATH}/
      - GF_SERVER_DOMAIN=$HOST
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=(Host(`$HOST`) &&
        PathPrefix(`$DASH_PATH`))"

  traefik:
    image: traefik:v2.5
    ports:
      - $PORT:80
      - 8080:8080
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  grafana-data: null
  postgres-data:
    external: true
