{
 "title": "Degrad Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Whether", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  temperature\nFROM whether\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  pressure\nFROM whether\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  humidity\nFROM whether\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  }
 ]
}